jobs:
  include:
    - language: ruby
      rvm: 2.3.3
      install:
        - gem install bundle
        - bundle install
      script: bundle exec jekyll build
    - language: node_js
      node_js: node

    - stage: deploy
      language: node_js
      node_js: node
      script: true
      # deploy:
      #   provider: pages
      #   skip_cleanup: true
      #   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
      #   on:
      #     branch: master

  fast_finish: true

cache:
  apt: true

notifications:
  email: false
