language: ruby
rvm:
  - 2.2

before_install:
  - gem install activesupport -v '~> 4.2'
  - gem install html-proofer

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

notifications:
  email: false
