language: ruby
rvm:
  - 2.1

before_install:
  - gem install html-proofer

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
