#
# Site configuration flags
# Jekyll (https://jekyllrb.com/)
#

# Site info
title: Créations Colombaro
version: 3.0.0
repository: LeoColomb/leocolomb.github.io
color: "#111111"
assetsurl: /assets
# theme: leocolomb-sites

# Author
author: LeoColomb
twitter:
  username: LeoColomb
fullname: Léo Colombaro

# Used for SEO
logo: /assets/icon/favicon.png

# Front Tools
google_analytics: UA-27779657-1

# Engines
permalink: /blog/:title/
paginate: 10
paginate_path: blog/page/:num
sass:
  style: :compressed
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

# Collections
collections:
  sections:
    output: false

# Plugins
plugins:
  - jemoji
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-octicons
  - jekyll-avatar

# Excluded files
exclude:
  - Gemfile*
  - LICENSE
  - README.md
  - node_modules
  - package*
