#
# Site configuration flags
# Jekyll (http://jekyllrb.com/)
#

# Site info
name: Créations Colombaro
description: colombaro.fr
version: 1.0.0
repository: LeoColomb/leocolomb.github.io
color: "#111111"
# theme: leocolomb-sites

# Author
author: LeoColomb
twitter:
  username: LeoColomb
fullname: Léo Colombaro

# Used for Sitemap.xml and your RSS feed
url: http://colombaro.fr
baseurl: ""
assetsurl: /assets

# Used for SEO
logo: /assets/icon/favicon.png

# Front Tools
google_analytics: UA-27779657-1

# Engines
permalink: /blog/:title/
paginate: 10
paginate_path: blog/page/:num
sass:
  style: :compressed

# Collections
collections:
  trips:
    output: true
    permalink: /road/:name/
  people:
    output: true
    permalink: /:name/

# Generation default options
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      category: blog
      layout: post
      sitemap: false
      color: "#542437"
      animation: wipeH
  -
    scope:
      path: road
    values:
      category: road
      layout: trip
      sitemap: false
      color: "#53777a"
      animation: wipeV
  -
    scope:
      path: ""
      type: people
    values:
      category: people
      layout: person
      title: À propos
      sitemap: false
      color: "#c02942"
      animation: cerclize
      icons:
        - social-github
        - social-linkedin
        - social-twitter
        - social-vimeo
        - social-behance
  -
    scope:
      path: code
    values:
      category: code
      color: "#d95b43"
      animation: cerclize
  -
    scope:
      path: bookmarks
    values:
      category: bookmarks
      color: "#ecd078"
      animation: cerclize

# Plugins
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
