#
# Site configuration flags
# Jekyll (http://jekyllrb.com/)
#

# Site info
name: Créations Colombaro
description: Léo Colombaro &middot; colombaro.fr
version: 1.0.0
author: Léo Colombaro

# Front Tools
disqus:
google_analytics: UA-27779657-1

# Used for Sitemap.xml and your RSS feed
url: http://colombaro.fr
baseurl: ""
assetsurl: "/assets"

# Collections
collections:
  trips:
    output: true
    permalink: /road/:title/

# Generation default options
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: ""
      type: "trips"
    values:
      layout: "trip"
      category: "road"

# Engines
permalink: /blog/:title/
paginate: 10
paginate_path: "blog/page/:num"
sass:
  style: :compressed

# Plugins
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
