#
# Site configuration flags
# Jekyll (http://jekyllrb.com/)
#

# Site info
name: Créations Colombaro
description: Léo Colombaro &middot; colombaro.fr
version: 1.0.0
author:
  name: Léo Colombaro
  uri: http://colombaro.fr/leo
color: "#0d0045"

# Front Tools
disqus:
google_analytics: UA-27779657-1

# Used for Sitemap.xml and your RSS feed
url: http://colombaro.fr
baseurl: ""
assetsurl: "/assets"

# Engines
permalink: /blog/:title/
paginate: 10
paginate_path: "blog/page/:num"
sass:
  style: :compressed

# Collections
collections:
  trips:
    output: true
    permalink: /road/:name/
  about:
    output: true
    permalink: /:name/

# Generation default options
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "blog"
      layout: "post"
      sitemap: false
      color: "#542437"
      anim: "wipeH"
  -
    scope:
      path: "road"
    values:
      category: "road"
      layout: "trip"
      sitemap: false
      color: "#53777a"
      anim: "wipeV"
  -
    scope:
      path: ""
      type: "about"
    values:
      category: "about"
      layout: "person"
      title: "About"
      sitemap: false
      color: "#c02942"
      anim: "cerclize"
  -
    scope:
      path: "code"
    values:
      category: "code"
      color: "#d95b43"
      anim: "cerclize"
  -
    scope:
      path: "bookmarks"
    values:
      category: "bookmarks"
      color: "#ecd078"
      anim: "cerclize"

# Plugins
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bower.json
